### ISSUE TITLE
Migrate from Travis.org to GH actions

### ISSUE THREAD

**Issue by mdelapenya** [testcontainers/testcontainers-go#242]
How does this affect us? https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by gianarb** [comment]
I am slowly moving my project to GitHub action, so I am happy to see this happening if somebody has the bandwidth to do it

**Comment by Bablzz** [comment]
I did small yaml with actions
```
name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  shellcheck:
    runs-on: [ubuntu-latest]
    steps:

    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: ./scripts
        ignore: testresources
    
    - name: Run gofmt
      run: |
        ./scripts/checks.sh
  test_ubuntu:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x, 1.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        go get gotest.tools/gotestsum
    
    - name: modVerify
      run: go mod verify
      
    - name: modTidy
      run: go mod tidy

    - name: vet
      run: go vet ./...

    - name: gotestsum
      run: gotestsum --format short-verbose ./...

    - name: Test
      run: go test -v ./...
```
