### ISSUE TITLE
[Enhancement]: replace manual mocks

### ISSUE THREAD

**Issue by stevenh** [testcontainers/testcontainers-go#2765]
### Proposal

Replace all manual mocks with generated ones, as started by https://github.com/testcontainers/testcontainers-go/pull/2731

**Comment by mdelapenya** [comment]
We must make sure there is a build command to do this 🙏

**Comment by mdelapenya** [comment]
sure, the local build must do exactly the same as in the CI, so that developers can replicate what the CI does. So:
- adding a build command
- the CI uses a command to validate (simply checking the git state??), that can be used by developers to understand if they missed anything

**Comment by stevenh** [comment]
Yer this would be an example of github action to validate:
```yaml
      - name: Install dependencies
        run: |
          go install github.com/vektra/mockery/v2@v2.42.2

      - name: Validate go mod / generate
        run: |
          go generate ./...
          go mod tidy
          git --no-pager diff && [[ 0 -eq $(git status --porcelain | wc -l) ]]
```
