### ISSUE TITLE
[Enhancement]: retire Go 1.17 from CI

### ISSUE THREAD

**Issue by mdelapenya** [testcontainers/testcontainers-go#529]
Go 1.17 is not supported since finished in 02 Aug 2022. See https://endoflife.date/go at 2022-09-16:

<img width="757" alt="Screenshot 2022-09-16 at 10 27 01" src="https://user-images.githubusercontent.com/951580/190593139-fcf0d8d1-2eb2-496c-b035-c3b92f2c442d.png">

### Proposal

My folks @v1v and @kuisathaverat already created an automated manner to bump the Go version. We may do the same as they do for Jenkins here: https://github.com/elastic/apm-pipeline-library/blob/main/vars/goVersion.groovy

But with a shell script:
```
git ls-remote --tags --refs https://github.com/golang/go | sed "s#.*refs/tags/##g" | grep "go*" | grep -v "[beat|rc]" | sed "s#^go##g" | sort --version-sort -r

1.19.1
1.19
1.18.6
1.18.5
1.18.4
1.18.3
1.18.2
1.18.1
1.18
1.17.13
1.17.12
1.17.11
1.17.10
1.17.9
1.17.8
1.17.7
1.17.6
1.17.5
1.17.4
1.17.3
1.17.2
1.17.1
1.17
1.16.15
1.16.14
1.16.13
1.16.12
1.16.11
1.16.10
1.16.9
1.16.8
1.16.7
1.16.6
1.16.5
1.16.4
1.16.3
1.16.2
1.16.1
1.16
1.15.15
1.15.14
1.15.13
1.15.12
1.15.11
1.15.10
1.15.9
1.15.8
1.15.7
1.15.6
1.15.5
1.15.4
1.15.3
1.15.2
1.15.1
1.15
1.14.15
1.14.14
1.14.13
1.14.12
1.14.11
1.14.10
1.14.9
1.14.8
1.14.7
1.14.6
1.14.5
1.14.4
1.14.3
1.14.2
1.14.1
1.14
1.13.15
1.13.14
1.13.13
1.13.12
1.13.11
1.13.10
1.13.9
1.13.8
1.13.7
1.13.6
1.13.5
1.13.4
1.13.3
1.13.2
1.13.1
1.13
1.12.17
1.12.16
1.12.15
1.12.14
1.12.13
1.12.12
1.12.11
1.12.10
1.12.9
1.12.8
1.12.7
1.12.6
1.12.5
1.12.4
1.12.3
1.12.2
1.12.1
1.12
1.11.13
1.11.12
1.11.11
1.11.10
1.11.9
1.11.8
1.11.7
1.11.6
1.11.5
1.11.4
1.11.3
1.11.2
1.11.1
1.11
1.10.8
1.10.7
1.10.6
1.10.5
1.10.4
1.10.3
1.10.2
1.10.1
1.10
1.9.7
1.9.6
1.9.5
1.9.4
1.9.3
1.9.2
1.9.1
1.9
1.8.7
1.8.6
1.8.5
1.8.4
1.8.3
1.8.2
1.8.1
1.8
1.7.6
1.7.5
1.7.4
1.7.3
1.7.2
1.7.1
1.7
1.6.4
1.6.3
1.6.2
1.6.1
1.6
1.5.4
1.5.3
1.5.2
1.5.1
1.5
1.4.3
1.4.2
1.4.1
1.4
1.3.3
1.3.2
1.3.1
1.3
1.2.2
1.2.1
1.2
1.1.2
1.1.1
1.1
1.0.3
1.0.2
1.0.1
1
```

**Comment by kuisathaverat** [comment]
take a look at https://www.updatecli.io/docs/plugins/resource/github_release/ we are testing it for the test clusters and works fine. This is an example to bump the kind version from a GitHub release

```
---
title: Update Tools
scms:
  githubConfig:
    kind: "github"
    spec:
      user: '{{ requiredEnv "GIT_USER" }}'
      email: '{{ requiredEnv "GIT_EMAIL" }}'
      owner: "elastic"
      repository: "my-github-repo"
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "GIT_USER" }}'
      branch: "main"
pullrequests:
  chart:
    kind: github
    scmid: githubConfig
    targets:
      - updateKind
    spec:
      labels:
        - dependencies
sources:
  lastKind:
    kind: githubrelease
    spec:
      owner: "kubernetes-sigs"
      repository: "kind"
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "GIT_USER" }}'
      versionFilter:
        kind: latest
    transformers:
      - trimprefix: "v"
targets:
  updateKind:
    name: "Update Kind"
    sourceid: lastKind
    scmid: githubConfig
    kind: yaml
    spec:
      file: "ansible/roles/k8s-kind/defaults/main.yml"
      key: "kind_version"
```
